name: "📐 Spec Change (OpenAPI)"
description: Propose a change to contracts (OpenAPI/spec)
labels: ["area:contracts", "spec:openapi", "type:feature"]
body:
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      placeholder: "Добавить /listings/{id}/publish: 202 Accepted + статус..."
    validations: { required: true }
  - type: textarea
    id: breaking
    attributes:
      label: Breaking Impact
      description: Есть ли breaking changes? Миграционный путь?
      placeholder: "Нет / Да, переименовать поле ..., сохранить алиас 1 минор..."
    validations: { required: true }
  - type: textarea
    id: examples
    attributes:
      label: Examples
      placeholder: "Примеры запросов/ответов, RFC7807 ошибки"
    validations: { required: true }
